customhost = "employee.cm13buus1fpf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "lawkuanteng-employee"
customregion = "us-east-1"
